Updating a distribution should not wipe existing settings
govuk-paas/paas-cdn-broker pull request #34
Opened 2020-04-16 12:19 UTC by tlwr

What
----

A salient commit message content which describes the what and the why:

```
UpdateOptions should be pointers

If you have a struct like

type UpdateOptions struct {
	Domain     string   `json:"domain"`
	DefaultTTL int64    `json:"default_ttl"`
	Cookies    bool     `json:"cookies"`
	Headers    []string `json:"headers"`
}

And you unmarshal '{}' into it

then the struct will have default values of "" for a string, 0 for an
int64, [] for an array, etc

If you have a struct like

type UpdateOptions struct {
	Domain     *string   `json:"domain,omitempty"`
	DefaultTTL *int64    `json:"default_ttl,omitempty"`
	Cookies    *bool     `json:"cookies,omitempty"`
	Headers    *[]string `json:"headers,omitempty"`
}

And you unmarshal {}' into it

then the struct will have nil values for *string, *int64, *[] etc

This is important. Currently if you

$ cf update-service my-cdn-route -c '{"domain": "my.domain.com", "headers": ["Accept", "Authorization"]}'

Then the headers will be set correctly

Then later, you do

$ cf update-service my-cdn-route -c '{"domain": "my.domain.com,my.otherdomain.com"}'

The resultant CDN distribution will have the headers reset

Now this not the case because we can distinguish between an empty list
and a not-provided list. This can be formalised as the difference
between Bool and Maybe<Bool>, where nil or not functions as the Maybe
monad.
```

How to review
----

Code review, commit by commit - I can squash afterwards in necessary.

Test in [tlwr development environment](https://admin.tlwr.dev.cloudpipeline.digital/):
- [ ] Create
- [ ] Update `-c {"cookies": false}` - check that cookies are set not to forward
- [ ] Update `-c {"cookies": true}` - check that cookies are set to forward
- [ ] Update `-c {"cookies": false}` - check that cookies are set to forward
- [ ] Update `-c {"headers": ["Authorization"]}` - check that the Host and Authorization headers are forwarding, and that the cookies are set to forward
- [ ] Update `-c {"default_ttl": 5}` - check that default TTL is updated, but the Headers and Cookies have not been changed
- [ ] Update to add a new domain
- [ ] Delete

Deploy [this commit](https://github.com/alphagov/paas-cf/commit/9e86e8b40a42db0732a978ebfd9b000e4558211a) to your development environment, should you wish to test it there

Who can review
----

Not @tlwr

2020-04-21 15:05 UTC, AP-Hunt commented
Manual testing works as expected

2020-04-21 15:24 UTC, AP-Hunt requested changes
I think we could improve the naming of the header-related tests in `broker/broker_provision_test.go` and `broker/broker_update_test.go` to better communicate that

1. You can't say "*" AND "Host"
2. It's OK to say specify the "Host" header in both ways
3. The "Host" header is always included

2020-04-21 15:24 UTC, AP-Hunt commented on broker/broker.go
> +func (b *CdnServiceBroker) parseProvisionDetails(details brokerapi.ProvisionDetails) (options Options, err error) {
I think typically we avoid specifying the names of the return variables in the signature, instead opting for explicit `return foo, bar` everywhere. That said, I'm not sure we have a set convention for it.

2020-04-21 15:24 UTC, AP-Hunt commented on broker/broker.go
>  func (b *CdnServiceBroker) parseUpdateDetails(details brokerapi.UpdateDetails) (options Options, err error) {
Same return arg names point here

2020-04-21 15:24 UTC, AP-Hunt commented on broker/broker_update_test.go
> +	defaultTTLNotPassed       *int64
I like this

2020-04-23 13:59 UTC, tlwr commented
Removed named parameters in c0dc2d7

Updated test descriptions in 36565f9

2020-04-27 10:13 UTC, AP-Hunt approved these changes

2020-04-27 14:59 UTC, merged